# Generated by Django 3.2.9 on 2021-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Oczekuje', 'Oczekuje'), ('W trakcie', 'W trakcie'), ('Naprawiono', 'Naprawiono'), ('Odrzucone', 'Odrzucone')], default='Oczekuje', max_length=50),
        ),
    ]
