# Generated by Django 3.2.9 on 2021-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
